[package]
author = "Juraj Michalek <juraj.michalek@espressif.com>"
name = "csv-report-converter"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
csv = "1.3.0"
urlencoding = "2.1.3"
